feat: upgrade to Uno Platform 5 (#324)
Co-authored-by: Valera <50830352+ValeraFinebits@users.noreply.github.com>

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,6 +1,6 @@
 ###############################################################################
 #
-#   Copyright 2023 Eppie(https://eppie.io)
+#   Copyright 2024 Eppie(https://eppie.io)
 #
 #   Licensed under the Apache License, Version 2.0 (the "License");
 #   you may not use this file except in compliance with the License.
@@ -16,24 +16,96 @@
 #
 ###############################################################################
 
+---
+
 name: "Build solution"
 
-on:
-  push:
-    branches: [ "main" ]
-  pull_request:
-    branches: [ "main" ]
+on: # yamllint disable-line rule:truthy
   workflow_dispatch:
+    inputs:
+      framework:
+        type: choice
+        default: all
+        options:
+          - desktop
+          - wasm
+          - winui
+          - ios
+          - macos
+          - android
+          - uwp
+          - all
+      os:
+        type: choice
+        default: all
+        options:
+          - windows
+          - linux
+          - macos
+          - all
+
+  push:
+    branches:
+      - main
+      - release/**
+      - feature/296-upgrading-to-uno-platform-5 # temporarily
+  pull_request:
+    branches:
+      - main
+      - release/**
+      - feature/296-upgrading-to-uno-platform-5 # temporarily
 
 jobs:
 
-  build:
-    runs-on: windows-latest
+  prepare:
+    runs-on: ubuntu-latest
 
+    outputs:
+      matrix: ${{ steps.build-config.outputs.matrix }}
+
+    steps:
+      - name: Checkout
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+        with:
+          fetch-depth: 0
+
+      - name: Initializing default keywords
+        if: github.event_name != 'workflow_dispatch'
+        shell: bash
+        run: |
+          echo "BUILD_CONFIG_KEYWORDS=autobuild" >> $GITHUB_ENV
+
+      - name: Read input keywords
+        if: github.event_name == 'workflow_dispatch'
+        shell: bash
+        run: |
+          echo "BUILD_CONFIG_KEYWORDS=${{ github.event.inputs.framework }},${{ github.event.inputs.os }}" >> $GITHUB_ENV
+
+      - name: Select configs
+        id: build-config
+        uses: finebits/github-actions/toolset/select-configuration@4a126d80a11c5fdc83ce884d3d23dffb30bc4495 # v2.0.0
+        with:
+          json-file: ./.github/configurations/build.json
+          keywords: ${{ env.BUILD_CONFIG_KEYWORDS }}
+
+      - name: Check configs
+        shell: bash
+        run: |
+          length=$( echo '${{ steps.build-config.outputs.config-json }}' | jq '. | length' )
+
+          if(( $length == 0 )); then
+            echo "::error::No suitable build configuration found"
+            exit 1
+          fi
+
+  build:
+    name: ${{ matrix.build.framework }} ${{ matrix.os }} '${{ matrix.build.project }}'
+    needs: prepare
     strategy:
-      matrix:
-        configuration: [ Debug, Release ]
-        target: [ android, gtk, ios, macos, wasm, win-x64, win-x86, win-arm64 ]
+      fail-fast: true
+      matrix: ${{ fromJson(needs.prepare.outputs.matrix) }}
+
+    runs-on: ${{ matrix.os }}
 
     env:
       configuration: ${{ matrix.configuration }}
@@ -41,45 +113,64 @@ jobs:
 
       dotnet-version: '8.x'
 
-      name: Eppie.App
-      root-dirictory: src/Eppie.App
-
-      # template: root/name/name.target/name.target.csproj
-      project-file-template: '{0}/{1}.{2}/{1}.{2}.csproj'
-
     steps:
-    - name: Checkout
-      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
-      with:
-        fetch-depth: 0
-        submodules: recursive
+      - name: Checkout
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+        with:
+          fetch-depth: 0
+          submodules: recursive
 
-    - name: Setup .NET
-      uses: actions/setup-dotnet@3e891b0cb619bf60e2c25674b222b8940e2c1c25 # v4.1.0
-      with:
-        dotnet-version: ${{ env.dotnet-version }}
+      - name: Setup .NET
+        uses: actions/setup-dotnet@3e891b0cb619bf60e2c25674b222b8940e2c1c25 # v4.1.0
+        with:
+          dotnet-version: ${{ env.dotnet-version }}
 
-    - name: Setup msbuild
-      uses: microsoft/setup-msbuild@6fb02220983dee41ce7ae257b6f4d8f9bf5ed4ce # v2.0.0
+      - name: Setup msbuild
+        if: matrix.prerequisites.msbuild == 'true'
+        uses: microsoft/setup-msbuild@6fb02220983dee41ce7ae257b6f4d8f9bf5ed4ce # v2.0.0
 
-    - name: Initialize project file paths
-      id: init-projects
-      uses: ./.github/actions/project-map
-      with:
-        solution-file: "${{ format('{0}/{1}.sln', env.root-dirictory, env.name) }}"
-        android-project-file: "${{ format(env.project-file-template, env.root-dirictory, env.name, 'Mobile') }}"
-        gtk-project-file: "${{ format(env.project-file-template, env.root-dirictory, env.name, 'Skia.Gtk') }}"
-        ios-project-file: "${{ format(env.project-file-template, env.root-dirictory, env.name, 'Mobile') }}"
-        macos-project-file: "${{ format(env.project-file-template, env.root-dirictory, env.name, 'Mobile') }}"
-        wasm-project-file: "${{ format(env.project-file-template, env.root-dirictory, env.name, 'Wasm') }}"
-        windows-project-file: "${{ format(env.project-file-template, env.root-dirictory, env.name, 'Windows') }}"
+      - name: Setup the Uno Platform
+        if: matrix.prerequisites.uno-platform == 'true'
+        uses: finebits/github-actions/devhub/uno-platform/setup@4a126d80a11c5fdc83ce884d3d23dffb30bc4495 # v2.0.0
 
-    - name: Setup the Uno Platform
-      uses: ./.github/actions/setup-uno-platform
+      - name: Restore via dotnet
+        if: matrix.restore.tool == 'dotnet'
+        shell: bash
+        run: |
+          project='${{ matrix.restore.project }}'
+          extra_options='${{ matrix.restore.extra }}'
 
-    - name: Build
-      uses: ./.github/actions/build-uno-project
-      with:
-        project-map: ${{ steps.init-projects.outputs.map }}
-        configuration: ${{ env.configuration }}
-        target: ${{ env.target }}
+          dotnet restore $extra_options $project
+
+      - name: Restore via msbuild
+        if: matrix.restore.tool == 'msbuild' && runner.os == 'Windows'
+        shell: pwsh
+        run: |
+          $project='${{ matrix.restore.project }}'
+          $extra_options=$('${{ matrix.restore.extra }}' -split '\s+')
+
+          msbuild -target:Restore $extra_options $project
+
+      - name: Build via dotnet
+        if: matrix.build.tool == 'dotnet'
+        shell: bash
+        run: |
+          project='${{ matrix.build.project }}'
+          configuration='${{ matrix.build.configuration }}'
+          extra_options='${{ matrix.build.extra }}'
+          framework='${{ matrix.build.framework }}'
+          framework_option=$([ "$framework" != "" ] && echo "--framework=$framework" || echo "")
+
+          dotnet build --configuration=$configuration $framework_option $extra_options $project
+
+      - name: Build via msbuild
+        if: matrix.build.tool == 'msbuild' && runner.os == 'Windows'
+        shell: pwsh
+        run: |
+          $project='${{ matrix.build.project }}'
+          $configuration='${{ matrix.build.configuration }}'
+          $extra_options=$('${{ matrix.build.extra }}' -split '\s+')
+          $framework='${{ matrix.build.framework }}'
+          $framework_option=$( if($framework) {"-property:TargetFramework=$framework"} else {""} )
+
+          msbuild -target:Build -property:Configuration=$configuration $framework_option $extra_options $project
